name: Build and Test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-last
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: build code
        run: dotnet build src/BochagovaExam.csproj
  test:
    runs-on: ubuntu-last
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: run test
        run: dotnet test test/TestProject1.csproj
